### ISSUE TITLE
Can not scan the MRZ in passport

### ISSUE THREAD

**Issue by HTKT** [SwiftyTesseract/SwiftyTesseractRTE#3]
Thanks for the great library!

If i scan the less text with more zoom in, it worked well but I tried  to scan the passport MRZ code but the photo seems to very small then it can not scan the MRZ code. 

Can you tell me how to zoom in the text more bigger ?
Thanks

**Comment by Steven0351** [comment]
I’ll have to dig up my passport to see if I can reproduce the issue. Are you getting any results back or is it just perpetually trying to recognize the MRZ code? It may be fixed by an implementation detail of an internal struct that is performing image transformations

**Comment by Steven0351** [comment]
This appears that it could be a twofold issue: standard Tesseract .traineddata sets don't appear to be optimized for recognizing MVR codes, and the internal image processor was degrading the image quality. I have a [customData branch on SwiftyTesseract](https://github.com/SwiftyTesseract/SwiftyTesseract/tree/customData) that will be merged into master soon that will allow you to use a third party data set like the one published on [Exteris/tesseract-mrz](https://github.com/Exteris/tesseract-mrz) and I'll be merging a [fix](https://github.com/SwiftyTesseract/SwiftyTesseractRTE/tree/imageProcessorOptimization) soon for the image degradation.

**Comment by HTKT** [comment]
Thanks @Steven0351 . Any update for merging? Looking forward to new version 👍

**Comment by Steven0351** [comment]
I can merge these now, but I was trying to squeeze in the [iOS 9.0 support request](https://github.com/SwiftyTesseract/SwiftyTesseract/issues/6) that you made on SwiftyTesseract.

**Comment by Steven0351** [comment]
#4 should at least _help_ with this issue. The only problem that I seemed to come across when testing this on various passports is that some of the passport backgrounds will cause SwiftyTesseract to recognize some characters differently. If you face this issue, then you should look into creating your own custom image processor that conforms to `AVSampleProcessor`. Covering every image processing edge case is outside the scope of the library, which is why the `AVSampleProcessor` protocol is made public. Feel free to use `ImageProcessor` as a baseline if you need to go that route.

**Comment by HTKT** [comment]
Thanks @Steven0351 . I will look into AVSampleProcessor if got an issue with the passport background.
